apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ghk6st8vh-go 
  janus-idp.io/tekton: ghk6st8vh-go
  backstage.io/kubernetes-id: ghk6st8vh-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ghk6st8vh-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  