apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ghk6st8vh-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ghk6st8vh-go 
  name: ghk6st8vh-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ghk6st8vh-go 
